language: ruby
services:
  - redis-server
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
gemfile:
  - gemfiles/rails_31.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails_40.gemfile
script: bundle exec rake test
